# -*- coding: utf-8 -*-
[config]

# %%
# ======================= INPUTS SET BY THE USER =======================
# Names of experiment variables estimated from the input files and
# registered in the log file
var_names_production = trial_number, trial_id, interval_1, interval_2, interval_3, interval_4
var_names_perception = trial_number, trial_id, interval_1, interval_2, interval_3, interval_4, interval_5
var_names_notemporal = trial_number, trial_id, interval_1, interval_2, interval_3, interval_4, interval_5, target_shape
# List with order of presentation of variable names in the log file (Title line w/ variables to be registered) for every event
llog_var_names = session_number, run_number, trial_number, trial_id, condition, onset, duration, theoretical_isi/feedback, real_isi/feedback, rt, key
# Session type
sesstype = imaging session
# Root directory of the input files
inputs_root = ../inputs/imaging-sessions_inputs
# Main directory of the input files
prod_dir = inputs_production
percep_dir = inputs_perception
notemp_dir = inputs_notemporal
# Path for the audio files
audiowav_path = audio_stim
# Name of the audio files
audiowav_low = beep_220hz_mono
audiowav_medium = beep_440hz_mono
audiowav_high = beep_880hz_mono
# Audio files extension
ext = wav
# RGB colours
black = 0, 0, 0
dark_yellow = 230, 159, 0
dark_purple = 51, 34, 136
dark_gray = 70, 70, 70
gray = 127, 127, 127
# TTL key
TTL = t
# Waiting time (ms) after TTL and before beginning of the run (ms)
WAIT = 12000
# Keys for participant's feedback
INDEX_BUTTON = b
MIDDLE_BUTTON = y
# Warning messages for run number entered by the user
wm1 = "Please, enter a valid number."
wm2 = "The number entered is greater than the total number of runs!"
# Message for the end of the session
text_end_run = "End of run."
# Message for the end of the experiment
text_end_exp_one = "The End."
text_end_exp_two = "Thank you for your participation!"
# Durations of fixed block periods
cue = 320
stim_duration = 80
within_block_duration = 2000
baseline_duration = 6000
feedback_duration = 2000
score_display_duration = 2400
endsess_duration = 10000
between_tasks_duration = 6000
# Visual stimuli
triangle_angle = -60
# Threshold for rating scores
min_prod = 0.88
max_prod = 1.12
min_ntfd = 100
max_ntfd = 700
