# -*- coding: utf-8 -*-
[config]

# %%
# ======================= INPUTS SET BY THE USER ==============================

# RGB colours
black = 0, 0, 0
dark_yellow = 230, 159, 0
dark_purple = 51, 34, 136
dark_gray = 70, 70, 70
gray = 127, 127, 127
dark_red = 153, 0, 0
blue = 0, 90, 181
# Path for the audio files
audiowav_path = audio_stim
# Name of the audio files
audiowav_low = beep_220hz_mono
audiowav_medium = beep_440hz_mono
audiowav_high = beep_880hz_mono
audiowav_soft = beep_440hz_amp0p16_mono
# Audio files extension
ext = wav
# Visual stimuli
triangle_angle = -60
# Keys for participant's feedback
INDEX_BUTTON = o
MIDDLE_BUTTON = p
# Feedback Box Text
line1 = "Great!"
line2 = "Your response was accurate."
line3 = "Your response was correct."
line4 = "Your response was not accurate."
line5 = "Your response was not correct."
line6 = "You were too fast."
line7 = "You were too fast and your response was not correct."
line8 = "Try to pay attention before giving an answer."
line9 = "Be faster!"
line10 = "You were too slow and your response was not correct."
line11 = "You can try again."
# Threshold for rating scores
min_prod = 0.88
max_prod = 1.12
min_ntfd = 100
max_ntfd = 700
