# -*- coding: utf-8 -*-
[config]

# %%
# ====================== SETTINGS FOR MAIN MENU ========================
# Title of the protocol
protocol_title = Timing Domain Task Battery - TDTB
# Main-menu options
instruct_prod = 1) Instructions for Production Tasks
instruct_prod_explicit = 2) Instructions for Production Tasks with explicit instruction
instruct_percep = 3) Instructions for Perception Tasks
instruct_percep_explicit = 4) Instructions for Perception Tasks with explicit instruction
instruct_notemp = 5) Instructions for No-Temporal FD Tasks
instruct_notemp_explicit = 6) Instructions for No-Temporal FD Tasks with explicit instruction
instruct_notemp_rand = 7) Instructions for No-Temporal FD Tasks with Random Condition
instruct_notemp_rand_explicit = 8) Instructions for No-Temporal FD Tasks with Random Condition with explicit instruction
prodAV_img = 9) Production Audio/Visual - imaging
prodVA_img = 10) Production Visual/Audio - imaging
percepAV_img = 11) Perception Audio/Visual - imaging
percepVA_img = 12) Perception Visual/Audio - imaging
notempAV_img = 13) No-Temporal FD Audio/Visual - imaging
notempVA_img = 14) No-Temporal FD Visual/Audio - imaging
audiprod_train = 15) Audio Production - training
audiprod_train_explicit = 16) Auditory Production - explicit training
audiprod_behav = 17) Audio Production - behavioral
audipercep_train = 18) Audio Perception - training
audipercep_train_explicit = 19) Auditory Perception - explicit training
audipercep_behav = 20) Audio Perception - behavioral
audinotemp_train = 21) Audio No-Temporal FD - training
audinotemp_train_explicit = 22) Auditory No-Temporal FD - explicit training
audinotemp_behav = 23) Audio No-Temporal FD - behavioral
viprod_train = 24) Visual Production - training
viprod_train_explicit = 25) Visual Production - explicit training
viprod_behav = 26) Visual Production - behavioral
vipercep_train = 27) Visual Perception - training
vipercep_train_explicit = 28) Visual Perception - explicit training
vipercep_behav = 29) Visual Perception - behavioral
vinotemp_train = 30) Visual No-Temporal FD - training
vinotemp_train_explicit = 31) Visual No-Temporal FD - explicit training
vinotemp_behav = 32) Visual No-Temporal FD - behavioral
exit = 33) Exit
# Note
note = "Attention: Please, wait a few moments after selecting your option."
# RGB colours
black = 0, 0, 0
gray = 127, 127, 127
dark_purple = 51, 34, 136
# Display next task in auto version
autotxt_duration = 1250